server:
  build: ./
  ports:
    - "3000:3000"
  volumes:
    - ./server/:/var/www/
  links:
    - redis
  environment:
    TERM: xterm
  command: ["node", "/var/www/index.js"]

redis:
  image: redis
  ports:
    - "6379:6379"
